name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
    paths:
      - 'ui/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: \Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: ./ui
        run: npm install
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          VITE_API_URL: https://api.blindtech.ices.edu.np
          VITE_WS_URL: wss://api.blindtech.ices.edu.np/ws
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ui/dist --project-name=blindtech
